packaging_format = 2

id = "sitemagiccms"
name = "Sitemagic CMS"
description.en = "Content Management System"
description.fr = "Système de gestion de contenu"

version = "4.4.2~ynh5"

maintainers = []

[upstream]
license = "FSFULLR"
website = "https://sitemagic.org/"
admindoc = "https://sitemagic.org/sites/cms-guide/"
code = "https://github.com/Jemt/SitemagicCMS"

[integration]
yunohost = ">= 11.2.29"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/sitemagic"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["da", "de", "el", "fr", "en", "sr"]
    default = "fr"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://sitemagic.org/index.php?SMExt=SMDownloads&SMDownloadsFile=SitemagicCMS442.zip"
        sha256 = "8d4e64b47e9bdcf037e523ce909392a07fe97620ac9f30772b3b1fc1542cd07a"
        in_subdir = false

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php7.4-mysql, php7.4-xml, php7.4-mbstring"

    [resources.database]
    type = "mysql"
